#!/bin/sh

EMAIL="dave@thesmithfam.org"
SUBJECT="isprinkle notification"
MESSAGE="The isprinkle-server is not running. Shutting down all valves (if any are running)."

while true; do

    if ! ps -eaf | grep isprinkle-server | grep -v grep >/dev/null 2>&1; then
        isprinkle-control --all-off
        RET=$?
        if which mail >/dev/null; then
            echo -e "$MESSAGE\n\nisprinkle-control exit status: $RET" |
                mail -s "$SUBJECT" "$EMAIL"
        else
            echo "  Error: No mail binary found to send email"
        fi
    fi

    sleep 60

done
