#!/usr/bin/python

import os, sys, time, signal

from webservice      import iSprinkleWebService
from wateringservice import iSprinkleWateringService
from model           import iSprinkleModel

shutdown_requested = 0

THREAD_TIMEOUT_SECONDS = 5.0

def handle_sigterm(signal, func=None):
    print 'Received SIGTERM'
    global shutdown_requested
    shutdown_requested = 1

if __name__ == '__main__':

    signal.signal(signal.SIGTERM, handle_sigterm)

    model = iSprinkleModel()

    try:

        webservice = iSprinkleWebService(model)
        webservice.start()

        wateringservice = iSprinkleWateringService(model)
        wateringservice.start()

    except IOError as (errno, strerror):
        print 'Could not startup: %s, code %d.' % (strerror, errno)
        sys.exit()
    except:
        print 'Could not startup: unknown error'
        sys.exit()

    try:
        while shutdown_requested == 0:
            time.sleep(1.0)
    except KeyboardInterrupt:
        pass

    webservice.stop()
    wateringservice.stop()

    webservice.join(THREAD_TIMEOUT_SECONDS)
    wateringservice.join(THREAD_TIMEOUT_SECONDS)
