#!/usr/bin/python

import os, sys, time, signal

from webservice      import iSprinkleWebService
from wateringservice import iSprinkleWateringService

stop_requested = 0

def handle_sigterm(signal, func=None):
    print 'Received SIGTERM'
    global stop_requested
    stop_requested = 1

if __name__ == '__main__':

    signal.signal(signal.SIGTERM, handle_sigterm)

    webservice = iSprinkleWebService()
    webservice.start()
    wateringservice = iSprinkleWateringService()
    wateringservice.start()

    try:
        while stop_requested == 0:
            time.sleep(1.0)
    except KeyboardInterrupt:
        pass

    webservice.stop()
    wateringservice.stop()
    webservice.join()
    wateringservice.join()
