#!/bin/bash

set -e

if [ -z "$1" -a -z "$2" ]; then
    echo "Usage: $0 <zone> <minutes> [<zone> <minutes>] ..."
    exit 1
fi

while [ -n "$1" ]; do
    zone=$1
    minutes=$2
    let seconds=$minutes*60
    shift
    shift

    echo "Runing zone '$zone' for '$minutes' minutes"
    isprinkle-control --run-zone $zone
    sleep $seconds
    isprinkle-control --all-off
    echo "Turning off zone '$zone'"
    sleep 3
done
